
dt = read.table('FrecoveryDiversity.txt', header=T)
dt$Group = ordered(dt$Group, levels=c('CK','E-liquid','Cigarette'))
result = kruskal.test(shannon ~ Group, data = dt)
kw_result  = data.frame(unclass(result), check.names = FALSE, stringsAsFactors = FALSE)
write.table(kw_result,file = "Frecovery_kruskal_shannon.txt", sep = "\t",quote = F,col.names=NA)
pairwise_wilcox = pairwise.wilcox.test(dt$shannon, dt$Group, p.adjust.method = "BH")
pairwise_wilcox = data.frame(unclass(pairwise_wilcox), check.names = FALSE, stringsAsFactors = FALSE)
write.table(pairwise_wilcox,file = "Frecovery_pairwise_wilcox_shannon.txt", sep = "\t", quote = F,col.names=NA)

dt = read.table('MrecoveryDiversity.txt', header=T)
dt$Group = ordered(dt$Group, levels=c('CK','E-liquid','Cigarette'))
result = kruskal.test(shannon ~ Group, data = dt)
kw_result  = data.frame(unclass(result), check.names = FALSE, stringsAsFactors = FALSE)
write.table(kw_result,file = "Mrecovery_kruskal_shannon.txt", sep = "\t",quote = F,col.names=NA)
pairwise_wilcox = pairwise.wilcox.test(dt$shannon, dt$Group, p.adjust.method = "BH")
pairwise_wilcox = data.frame(unclass(pairwise_wilcox), check.names = FALSE, stringsAsFactors = FALSE)
write.table(pairwise_wilcox,file = "Mrecovery_pairwise_wilcox_shannon.txt", sep = "\t", quote = F,col.names=NA)

dt = read.table('FrecoveryDiversity.txt', header=T)
dt$Group = ordered(dt$Group, levels=c('CK','E-liquid','Cigarette'))
result = kruskal.test(number ~ Group, data = dt)
kw_result  = data.frame(unclass(result), check.names = FALSE, stringsAsFactors = FALSE)
write.table(kw_result,file = "Frecovery_kruskal_number.txt", sep = "\t",quote = F,col.names=NA)
pairwise_wilcox = pairwise.wilcox.test(dt$number, dt$Group, p.adjust.method = "BH")
pairwise_wilcox = data.frame(unclass(pairwise_wilcox), check.names = FALSE, stringsAsFactors = FALSE)
write.table(pairwise_wilcox,file = "Frecovery_pairwise_wilcox_number.txt", sep = "\t", quote = F,col.names=NA)
